name: Build and Deploy to GitHub Pages

on:
  push:
    branches: ["master"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Add any setup steps required for your project, such as setting up Node.js:
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # Specify the Node.js version you need

      # Install your dependencies here:
      - name: Install Dependencies
        run: npm install

      # Build your project here:
      - name: Build Project
        run: npm run build # Or the correct build command for your project

      # Deploy to GitHub Pages:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v3
        with:
          # This should be the path to your build output directory:
          deployment_repository: ${{ github.repository }}
          deployment_branch: gh-pages # The branch GitHub Pages will serve from
          publish_dir: ./dist # The directory that contains your built site
